### ISSUE TITLE
Incorrect 0.3.0 on PyPI

### ISSUE THREAD

**Issue by kyriog** [Relrin/sanic-mongodb-extension#12]
It seems that the 0.3.0 version of sanic-mongodb-extension on PyPI is incorrect: according to both what's installed with pip or downloaded from pypi.org website, the version 0.3.0 still requires `umongo==1.0.0`, instead of 2.0.0 according to the source code.

**Comment by Relrin** [comment]
Hi, @kyriog 

Thank you for opening an issue here.

I have re-uploaded the fixed package (as the 0.4.0 version) with correct dependency list. Also I updated version of the used packages to the latest releases.

If you face with any issues related to this package later on, please, let me know.
