### ISSUE TITLE
umongo.exceptions.NoDBDefinedError: init must be called to define a db

### ISSUE THREAD

**Issue by heronrs** [Relrin/sanic-mongodb-extension#7]
As soon as I move the Artist document to its own document.py model from the README example I start getting `umongo.exceptions.NoDBDefinedError: init must be called to define a db.`

Any idea what might be happening ?

**Comment by Relrin** [comment]
Hello, @heron182 

Thank you for opening an issue.

As far as I remember, this exception raises when you're trying to use lazy clients without initializing them properly. Any lazy class of uMongo expects that the used database will be specified before the usage.
Everything that you need is to specify the used database and invoke the `init` method of your lazy instance, like this:
```python
from motor.motor_asyncio import AsyncIOMotorClient
from umongo import MotorAsyncIOInstance

client = AsyncIOMotorClient("mongodb://user:password@host:port/")
client = client["test_database"]
lazy_umongo = MotorAsyncIOInstance()
lazy_umongo.init(client)
```

As an example you can look into [Auth/Auth microservice](https://github.com/OpenMatchmaking/microservice-auth) code, where documents defined and store in the separate files from the actual usage. Also these files with code as examples ([documents.py](https://github.com/OpenMatchmaking/microservice-auth/blob/master/auth/app/microservices/documents.py) and [prepare_mongodb.py](https://github.com/OpenMatchmaking/microservice-auth/blob/master/auth/app/commands/prepare_mongodb.py#L50-L53)) will help you to find a solution.

**Comment by heronrs** [comment]
Thanks, I'll look into it!
